ignore failed optional deps (not ready)
zkat/cipm pull request #20
Opened 2017-09-10 06:57 UTC by boneskull

okay, so this will ignore failed optional deps by just eating the errors.  however, the optional packages are counted towards the total package count, and the object is passed on thru the promise chain as if nothing bad occurred, which might not be what we want.

IMO ignoring the failures is probably sufficient (instead of trying to prune the tree), because if we're running on CI, who cares, right?

what'd be your preferred strategy to test this behavior?

I had to nest the promises or the `tap()` calls wouldn't work.

2017-09-10 09:54 UTC, zkat requested changes
On top of the comment I added, this should probably be repeated for the `preinstall` script a few lines up, which might also fail.

2017-09-10 09:54 UTC, zkat commented on index.js
>          this.pkgCount++
Would be nice if you added a `this.failedPkgCount`, and incremented that, maybe? Would be good to report it...

2017-09-10 10:36 UTC, mikesherov requested changes
Thanks for contributing! Looking good so far, minus tests. There are some good tests in the test suite that mock out extraction so you could make a failing install script combined with a successful extraction.

2017-10-11 09:06 UTC, zkat commented
Closing this in favor of #27, which does all the smart tree building and removal stuff. I had to go and write [`npm-logical-tree`](https://npm.im/npm-logical-tree) and do a mark-and-sweep GC to get this working right, so I think it was a bit bigger than originally though. Sorry about that.

Seriously, though, thanks for the contribution! I really hope to see more patches from you in the future. This was super appreciated. <3

2017-10-11 09:06 UTC, closed without merging