feat(bin): link bins and run scripts
zkat/cipm pull request #25
Opened 2017-10-08 02:56 UTC by zkat

Fixes: #4

2017-10-08 03:20 UTC, mikesherov requested changes
Looks good, just super minor stuff missing

2017-10-08 03:20 UTC, mikesherov commented on index.js
> +          ignoreScripts: this.config.lifecycleOpts.ignoreScripts,
There’s a few more options needed here that get passed from bin-links to gentleFS

2017-10-08 03:20 UTC, mikesherov commented on index.js
> -      .then(() => readJson(childPath, 'package.json'))
Can you delete the readJson function now?

2017-10-08 03:20 UTC, mikesherov commented on index.js
> +          ignoreScripts: this.config.lifecycleOpts.ignoreScripts,
I have them in my local copy at work. Will send Monday, or you can figure it out :-). At least one is: `name: cipm`

2017-10-08 03:26 UTC, mikesherov commented on index.js
> -      .then(() => readJson(childPath, 'package.json'))
Nvm, you need it to read the lock and shrink wrap files!

2017-10-09 01:23 UTC, zkat commented
Should be good to re-review. I don't think there's any missing opts here.

2017-10-09 02:17 UTC, mikesherov approved these changes

2017-10-09 14:23 UTC, mikesherov commented on index.js
> +          prefix: this.prefix,
I'm not sure this is right, btw. opts.prefix is used for `man` linking, which is usually like `/usr/local` in npm I think. I should rename this property `manPrefix`. Probably ok to land for now, but we should fix this before launch.

```
function linkMans (pkg, folder, parent, gtop, opts, cb) {
  if (!pkg.man || !gtop || process.platform === 'win32') return cb()

  var manRoot = path.resolve(opts.prefix, 'share', 'man')
  opts.log.verbose('linkMans', 'man files are', pkg.man, 'in', manRoot)
```

2017-10-09 17:05 UTC, merged