fix(lifecycle): detect binding.gyp for default install lifecycle
zkat/cipm pull request #46
Opened 2018-04-07 04:14 UTC by caleblloyd

This is a fix to detect if `binding.gyp` exists in a package without an `install` lifecycle script, and if so adds the [default install lifecycle script](https://docs.npmjs.com/misc/scripts#default-values)

I opted to check for `binding.gyp` using `statAsync` instead of [readPkgJson.extras](https://github.com/npm/read-package-json/blob/c1b24b0b7f4cc2f096de80b64779d976add42323/read-json.js#L136) because the only thing needed here was `binding.gyp` detection, not everything else provided by `readPkgJson.extras`

2018-04-07 20:25 UTC, zkat requested changes
Thanks for this patch! I'm glad you found this and fixed it 💚

The patch looks good, but I'm wondering if it makes sense to move this to the `updateJson` method -- that's usually used to add the `_from` field but you can use it to do the binding.gyp check.

The main difference is that buildTree happens serially, so those statAsync calls are going to block iteration.

My strongest preference is to have `pacote` itself detect `binding.gyp` on extract, which would allow us to skip the stats altogether (they're pretty expensive, performance-wise, and this one is going to be very common)

2018-04-08 02:34 UTC, caleblloyd commented
I've moved the logic to `updateJson` and even figured out how to write a test for it :tada: Changes are ready for review

2018-04-08 20:42 UTC, zkat approved these changes
Awesome! And I tested this locally and it seems to not have any noticeable performance impact. Thanks a bunch for this and the changes! 🚢

2018-04-08 20:42 UTC, merged

2018-04-08 20:44 UTC, zkat commented
I've merged this and it's been released as `libcipm@1.6.2`. It should be available in the next npm release.

2018-04-08 21:00 UTC, caleblloyd commented
Great, thanks!  I've patched this fix into my workflow and it seems to fix the original issue with no side effects.  Looking forward to pulling it down in the next npm release!